package com.vaultcall.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents the on-device transcription of a voicemail.
 *
 * Generated by the Whisper ONNX model running locally on the device.
 * No audio or text data ever leaves the device.
 *
 * @property voicemailId Foreign key reference to the parent [Voicemail].
 * @property text The full transcribed text.
 * @property language Detected language code (e.g., "en", "hi").
 * @property confidence Average log probability from the model, 0.0 to 1.0.
 * @property keywords JSON array of flagged keywords found in the transcript.
 * @property createdAt Timestamp when this transcript was generated.
 */
@Entity(
    tableName = "transcripts",
    indices = [Index("voicemailId")]
)
data class Transcript(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val voicemailId: Long,
    val text: String,
    val language: String = "en",
    val confidence: Float,
    val keywords: String,
    val createdAt: Long = System.currentTimeMillis()
)
