package com.vaultcall.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a voicemail recording stored in the local database.
 *
 * All audio files referenced by [encryptedFilePath] are AES-256-GCM encrypted
 * and stored in the app's private directory.
 *
 * @property callerId The phone number of the caller.
 * @property callerName The contact name resolved from the device contacts, if available.
 * @property timestamp Unix timestamp in milliseconds when the voicemail was received.
 * @property durationSeconds Duration of the recording in seconds.
 * @property encryptedFilePath Absolute path to the encrypted .m4a file on disk.
 * @property isRead Whether the user has listened to this voicemail.
 * @property isArchived Whether the user has archived this voicemail.
 * @property triggerRule The name of the rule that triggered this voicemail, or null if manual.
 * @property isScreened Whether this voicemail was generated by auto-screening.
 */
@Entity(
    tableName = "voicemails",
    indices = [
        Index("callerId"),
        Index("timestamp")
    ]
)
data class Voicemail(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val callerId: String,
    val callerName: String?,
    val timestamp: Long,
    val durationSeconds: Int,
    val encryptedFilePath: String,
    val isRead: Boolean = false,
    val isArchived: Boolean = false,
    val triggerRule: String?,
    val isScreened: Boolean = false
)
